import { StyleSheet } from "react-native";
import { colors, fonts } from "@/src/theme/tokens";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  centerFill: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  header: {
    paddingHorizontal: 22,
    paddingBottom: 16,
  },
  topRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  topRowRight: {
    flexDirection: "row",
    gap: 10,
  },
  statsButton: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  statsButtonPressed: {
    backgroundColor: colors.hover,
  },
  invitePill: {
    height: 40,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  invitePillPressed: {
    backgroundColor: colors.hover,
  },
  invitePillLabel: {
    fontFamily: fonts.outfit500,
    fontSize: 14,
    color: colors.ink,
  },
  title: {
    fontFamily: fonts.outfit600,
    fontSize: 30,
    lineHeight: 32,
    letterSpacing: -0.9,
    color: colors.ink,
  },
  progressRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 12,
  },
  progressTrack: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.chip,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 4,
    backgroundColor: colors.mint,
  },
  progressLabel: {
    fontFamily: fonts.mono500,
    fontSize: 13,
    color: colors.muted,
  },

  scrollContent: {
    paddingHorizontal: 22,
    paddingTop: 4,
  },
  groupHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  groupLabel: {
    fontFamily: fonts.mono500,
    fontSize: 11,
    letterSpacing: 1.1,
    color: colors.muted,
  },
  groupHairline: {
    flex: 1,
    height: 1,
    backgroundColor: colors.line,
  },
  groupCount: {
    fontFamily: fonts.mono400,
    fontSize: 11,
    color: colors.disabledStrong,
  },
  reorderToggle: {
    fontFamily: fonts.outfit500,
    fontSize: 13,
    color: colors.mint,
  },
  reorderToggleRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginBottom: 12,
  },
  itemList: {
    gap: 8,
    marginBottom: 22,
  },
  reorderArrows: {
    gap: 4,
  },
  reorderArrowButton: {
    width: 28,
    height: 22,
    borderRadius: 8,
    backgroundColor: colors.surfaceRaised,
    alignItems: "center",
    justifyContent: "center",
  },
  reorderArrowButtonDisabled: {
    opacity: 0.4,
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 18,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  checkbox: {
    width: 26,
    height: 26,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.checkboxIdle,
    backgroundColor: "transparent",
  },
  checkboxChecked: {
    backgroundColor: colors.mint,
    borderColor: colors.mint,
  },
  itemTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  itemName: {
    fontFamily: fonts.outfit500,
    fontSize: 16.5,
    color: colors.ink,
  },
  itemNameChecked: {
    fontFamily: fonts.outfit400,
    color: colors.faint,
    textDecorationLine: "line-through",
  },
  itemMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 3,
  },
  itemQty: {
    fontFamily: fonts.mono400,
    fontSize: 12.5,
    color: colors.muted,
  },
  itemNote: {
    fontFamily: fonts.outfit400,
    fontSize: 12.5,
    color: colors.faint,
    flexShrink: 1,
  },

  emptyState: {
    alignItems: "center",
    paddingTop: 60,
  },
  emptyText: {
    fontFamily: fonts.outfit400,
    fontSize: 15,
    color: colors.muted,
    textAlign: "center",
  },

  finishCard: {
    marginTop: 8,
    padding: 24,
    borderRadius: 22,
    backgroundColor: colors.mintWash,
    alignItems: "center",
  },
  finishTitle: {
    fontFamily: fonts.outfit600,
    fontSize: 20,
    color: colors.mint,
  },
  finishBody: {
    fontFamily: fonts.outfit400,
    fontSize: 14,
    color: colors.muted,
    marginTop: 6,
  },
  clearButton: {
    marginTop: 16,
    height: 44,
    paddingHorizontal: 20,
    borderRadius: 14,
    backgroundColor: colors.mint,
    alignItems: "center",
    justifyContent: "center",
  },
  clearButtonLabel: {
    fontFamily: fonts.outfit600,
    fontSize: 15,
    color: colors.mintInk,
  },

  fab: {
    position: "absolute",
    right: 22,
    height: 56,
    paddingHorizontal: 22,
    borderRadius: 20,
    backgroundColor: colors.mint,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    shadowColor: "#5EE6A8",
    shadowOpacity: 0.25,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  fabPressed: {
    backgroundColor: "#7BEDB9",
  },
  fabLabel: {
    fontFamily: fonts.outfit600,
    fontSize: 16,
    color: colors.mintInk,
  },

  errorTitle: {
    fontFamily: fonts.outfit600,
    fontSize: 21,
    color: colors.ink,
    marginBottom: 8,
    textAlign: "center",
  },
  errorBody: {
    fontFamily: fonts.outfit400,
    fontSize: 15,
    color: colors.muted,
    textAlign: "center",
    marginBottom: 24,
    maxWidth: 280,
  },

  // Add/Edit item sheet
  sheetTitle: {
    fontFamily: fonts.outfit600,
    fontSize: 22,
    letterSpacing: -0.44,
    color: colors.ink,
    marginBottom: 16,
  },
  nameInput: {
    height: 56,
    borderRadius: 16,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.lineStrong,
    paddingHorizontal: 18,
    fontFamily: fonts.outfit500,
    fontSize: 17,
    color: colors.ink,
    marginBottom: 8,
  },
  nameError: {
    fontFamily: fonts.outfit400,
    fontSize: 13,
    color: colors.danger,
    marginBottom: 10,
  },
  sheetRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 20,
  },
  stepper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    height: 52,
    paddingHorizontal: 6,
    borderRadius: 16,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  stepperButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  stepperButtonPressed: {
    backgroundColor: "#262C33",
  },
  stepperButtonLabel: {
    fontFamily: fonts.outfit500,
    fontSize: 22,
    color: colors.muted,
  },
  stepperValue: {
    minWidth: 34,
    textAlign: "center",
    fontFamily: fonts.mono500,
    fontSize: 17,
    color: colors.ink,
  },
  noteInput: {
    flex: 1,
    minWidth: 0,
    height: 52,
    borderRadius: 16,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 16,
    fontFamily: fonts.outfit400,
    fontSize: 15,
    color: colors.ink,
  },
  aisleLabel: {
    fontFamily: fonts.mono500,
    fontSize: 11,
    letterSpacing: 0.66,
    textTransform: "uppercase",
    color: colors.muted,
    marginBottom: 10,
  },
  aisleChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 20,
  },
  aisleChip: {
    height: 38,
    paddingHorizontal: 14,
    borderRadius: 13,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: "center",
    justifyContent: "center",
  },
  aisleChipSelected: {
    backgroundColor: colors.mintWash,
    borderColor: "rgba(94,230,168,0.5)",
  },
  aisleChipLabel: {
    fontFamily: fonts.outfit500,
    fontSize: 13,
    color: colors.muted,
  },
  aisleChipLabelSelected: {
    color: colors.mint,
  },
  removeButton: {
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 6,
  },
  removeButtonLabel: {
    fontFamily: fonts.outfit500,
    fontSize: 15,
    color: colors.danger,
  },
  bulkToggle: {
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  bulkToggleLabel: {
    fontFamily: fonts.outfit500,
    fontSize: 14,
    color: colors.mint,
  },
  bulkInput: {
    height: 160,
    borderRadius: 16,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.lineStrong,
    paddingHorizontal: 18,
    paddingTop: 16,
    fontFamily: fonts.outfit400,
    fontSize: 16,
    color: colors.ink,
    marginBottom: 8,
    textAlignVertical: "top",
  },

  // Manage list sheet (rename / delete)
  sheetBody: {
    fontFamily: fonts.outfit400,
    fontSize: 15,
    color: colors.muted,
    marginBottom: 22,
  },
  manageMenuItem: {
    height: 56,
    borderRadius: 18,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.lineStrong,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  manageMenuItemLabel: {
    fontFamily: fonts.outfit500,
    fontSize: 16,
    color: colors.ink,
  },
  manageMenuItemDanger: {
    color: colors.danger,
  },
  removeButtonSolid: {
    height: 52,
    borderRadius: 18,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  removeButtonSolidLabel: {
    fontFamily: fonts.outfit500,
    fontSize: 15,
    color: colors.danger,
  },
  manageCancel: {
    height: 52,
    borderRadius: 18,
    backgroundColor: colors.surfaceRaised,
    alignItems: "center",
    justifyContent: "center",
  },
  manageCancelLabel: {
    fontFamily: fonts.outfit500,
    fontSize: 15,
    color: colors.ink,
  },
});

export default styles;
